import { PetFilter } from "../models/models";

const filterDatabase: PetFilter[] = [
  { key: "animal", value: "gato" },
  { key: "animal", value: "cachorro" },
  { key: "gender", value: "fêmea" },
  { key: "gender", value: "macho" },
  { key: "breed", value: "SRD" },
  { key: "breed", value: "ragdoll" },
  { key: "breed", value: "siamês" },
  { key: "breed", value: "persa" },
  { key: "breed", value: "siberiano" },
  { key: "breed", value: "british shorthair" },
  { key: "breed", value: "birmanês" },
  { key: "breed", value: "bulldog" },
  { key: "breed", value: "labrador" },
  { key: "breed", value: "golden retriever" },
  { key: "breed", value: "poodle" },
  { key: "breed", value: "rottweiler" },
  { key: "breed", value: "beagle" },
  { key: "breed", value: "yorkshire" },
  { key: "breed", value: "border collie" },
  { key: "breed", value: "dachshund" },
  { key: "breed", value: "pastor alemão" },
  { key: "breed", value: "outra raça" },
  { key: "size", value: "porte pequeno" },
  { key: "size", value: "porte médio" },
  { key: "size", value: "porte grande" },
  { key: "fur_height", value: "pelo baixo" },
  { key: "fur_height", value: "pelo médio" },
  { key: "fur_height", value: "pelo alto" },
  { key: "age_range", value: "menos de 1 ano" },
  { key: "age_range", value: "entre 1 e 3 anos" },
  { key: "age_range", value: "entre 3 e 7 anos" },
  { key: "age_range", value: "mais de 7 anos" },
  { key: "castrated", value: "castrado" },
  { key: "castrated", value: "não-castrado" },
  { key: "mood", value: "agitado" },
  { key: "mood", value: "calmo" },
];

export default filterDatabase;
